### ISSUE TITLE
Cannot import test-ai

### ISSUE THREAD

**Issue by Gyurmatag** [andytyler/playwright-ai#3]
Hi!

I am in a Next.js application and there is an error when I try to import { ai } from tests-ai:
![Képernyőfotó 2024-11-23 - 17 59 28](https://github.com/user-attachments/assets/c5550563-caa8-43e9-99c0-45db30ed8036)
![Képernyőfotó 2024-11-23 - 17 59 50](https://github.com/user-attachments/assets/c750ddee-d97a-4a52-ae3d-d3e3707c772e)

If i modify it to this:
`import { ai } from 'tests-ai/src';`
It wil llead me to this error:
![Képernyőfotó 2024-11-23 - 18 00 28](https://github.com/user-attachments/assets/48dd2f66-baca-4a0d-af67-711cee242318)

Please resolve this issue, because I want to use this package.

**Comment by andytyler** [comment]
This has been fixed - the bug was a problem at compile time.

fixed in v1.0.10
